language: python

python: 
  - "3.7"
  #- "3.8" # Don't work because psycopg2-binary

services:
  - mysql

env:
  -DJANGO=3.0 DB=mysql
  
install:
  - pip install -r requirements.txt

before_script: 
  - mysql -e 'create database test;' -u root
  
script: 
  - python manage.py test
